### ISSUE TITLE
Can't do npm install - bcrypt problem

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/dev-fortress-server#10]
When I do npm install I get this:

```
C:\code\dev-fortress-server>npm install

> bcrypt@0.8.7 install C:\code\dev-fortress-server\node_modules\bcrypt
> node-gyp rebuild


C:\code\dev-fortress-server\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Users\andy.SE\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\andy.SE\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andy.SE\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\code\dev-fortress-server\node_modules\bcrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andy.SE\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andy.SE\AppData\Roaming\npm-cache\_logs\2017-02-21T15_17_14_819Z-debug.log
```

**Comment by ShaydeNofziger** [comment]
@andymeneely This is a known issue with bcrypt and Windows compatibility. There are some additional pre-reqs Windows machines require. Can you confirm whether or not you have these dependencies installed?

https://github.com/kelektiv/node.bcrypt.js#dependencies

If you don't want to do that, it should work on macOS as-is

**Comment by andymeneely** [comment]
Ok I'll pursue that on Windows first and see how this goes.

**Comment by andymeneely** [comment]
Ok got gyp installed and then bcrypt using Option 1 here: https://github.com/nodejs/node-gyp

Now when I do a migrate it doesn't respect my sqlite installation. 

```
C:\code\dev-fortress-server>npm run migrate

> express-mvc-starter@0.0.0 migrate C:\code\dev-fortress-server
> knex migrate:latest

Using environment: development
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'C:\code\dev-fortress-server\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\dev-fortress-server\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client._driver (C:\code\dev-fortress-server\node_modules\knex\lib\dialects\sqlite3\index.js:65:12)
    at Client.initializeDriver (C:\code\dev-fortress-server\node_modules\knex\lib\client.js:211:26)
    at Client (C:\code\dev-fortress-server\node_modules\knex\lib\client.js:92:10)
    at Client_SQLite3 (C:\code\dev-fortress-server\node_modules\knex\lib\dialects\sqlite3\index.js:51:23)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andy.SE\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "migrate"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-mvc-starter@0.0.0 migrate: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-mvc-starter@0.0.0 migrate script 'knex migrate:latest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the express-mvc-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs express-mvc-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls express-mvc-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andy.SE\AppData\Roaming\npm-cache\_logs\2017-02-21T22_00_04_273Z-debug.log
```

**Comment by andymeneely** [comment]
And, when I do this:

```
C:\code\dev-fortress-server>npm install sqlite
express-mvc-starter@0.0.0 C:\code\dev-fortress-server
`-- sqlite@2.3.0
```

... I still get the above error after trying to migrate.

Same with sqlite3 too

**Comment by ShaydeNofziger** [comment]
After some digging, it looks like people have had success by deleting their `node_modules` directory and re-running `npm install`. Can you try that and see if it resolves the issue? It could be that the new binary isn't being updated since installing windowsbuildtools package.

If the above doesn't work, what exists at `.\node_modules\sqlite3\lib\binding\` in your local repo?
